### PR TITLE
[DO NOT MERGE] Small commit to facilitate the sandbox

### PR DESCRIPTION
**Pull request by Wynndow**

### CODE REVIEW

**Comment by Krenair** [comment]
(I had no idea there was a PR associated with this, I'm just pushing to the branch to deploy to the sandbox cluster)

**Comment by Wynndow** [comment]
This PR is only here to fix the issue with their needing to be a PR open for the github api to do it's thing in the Concourse pipeline, when checking approvals (I think that's the reason...).

**Comment by Krenair** [comment]
ahh yes I recall that being a thing for GSP on-demand cluster branches, ok :)

**Comment by Krenair** [comment]
PR should no longer be required given https://github.com/alphagov/gsp/pull/1053 + https://github.com/alphagov/tech-ops-cluster-config/pull/297

**Pull request closed without merging**
